<footer>
          <p><a href="https://10026thur1630g05.atlassian.net/jira/software/projects/SCRUM/boards/1?atlOrigin=eyJpIjoiNzhkY2NiMWFmOGY5NDcyNDk1NzAxOGMxY2ViMzljM2YiLCJwIjoiaiJ9" target="_blank" rel="noopener noreferrer">Jira Board</a></p>
          <p><a href="https://github.com/104001159/Applied-Web-Project.git" target="_blank" rel="noopener noreferrer">GitHub Repository</a></p>
          <p><a href="mailto:info@cartx.com.au">info@cartx.com.au</a></p>
</footer>
